### ISSUE TITLE
Desktop Width, Height

### ISSUE THREAD

**Issue by Kim-Gayoung** [kwanghoon/MySmallBasic#102]
Desktop의 Width와 Height는 Screen의 Size로 각 화면마다 다른 사이즈를 가질 수 있도록 해야될 것 같습니다.

static {
		Width = new DoubleV(1280);  // Need to fix!!
		Height = new DoubleV(640);
	}

Toolkit.getDefaultToolkit().getScreenSize()를 통한 getWidth(), getHeight()로 스크린의 사이즈를 가져올 수 있습니다.

**Comment by kwanghoon** [comment]
Commit   9901b69

Desktop의 Width와 Height를 Toolkit 클래스를 이용하여 설정하도록 변경

@KimGa-Young
