### ISSUE TITLE
Sound 라이브러리

### ISSUE THREAD

**Issue by Kim-Gayoung** [kwanghoon/MySmallBasic#104]
Sokoban.sb 진행 중

Sound의 stop에서 mp3가 null인 경우 아래와 같은 에러 발생
--
java.lang.NullPointerException
	at com.coducation.smallbasic.lib.Sound.Stop(Sound.java:210)

Sound가 File이 아닌 URL로 가져오는 경우 고려 필요
--
java.io.FileNotFoundException: http:\smallbasic.com\drop\soko\sokocute01.wav (파일 이름, 디렉터리 이름 또는 볼륨 레이블 구문이 잘못되었습니다)

**Comment by kwanghoon** [comment]
@Seyeong2  @KimGa-Young 
세영아, Sound 라이브러리에서 가영이가 올린 이슈를 확인해볼 수 있을까?

**Comment by Seyeong2** [comment]
네 수정하고있습니다!

**Comment by kwanghoon** [comment]
땡큐~

2017년 3월 3일 (금) 오후 10:45, Seyeong2 <notifications@github.com>님이 작성:

**Comment by kwanghoon** [comment]
@Seyeong2 
Seyoung, can you comment on what is the current status for resolving this issue?
