### ISSUE TITLE
Array 변수명을 출력할 때 발생하는 예외

### ISSUE THREAD

**Issue by moonyoungJo** [kwanghoon/MySmallBasic#124]
stack라이브러리를 개발할때 만든 테스트코드에서  그 당시에는 나타나지 않았던 예외가 발생하였습니다.

**문제가 되는 스몰베이직코드**
myArr[1] = 1
myArr[2] = 2
TextWindow.WriteLine("myArr.toString : " + myArr)

**스몰베이직에서의 출력결과**
myArr.toString : 1=1;2=2;

**My스몰베이직에서의 결과**
Exception in thread "main" com.coducation.smallbasic.InterpretException: PLUS 2nd operand unexpected1=1;2=2;
	at com.coducation.smallbasic.Eval.eval(Eval.java:282)
        .....

 ArrayV클래스의 toString 메소드는 알맞은 값(1=1;2=2;)을 리턴하고 있는 것을 확인하였습니다. 
eval클래스의 282번째 줄에서 예외가 발생하고 있습니다...

@kwanghoon

**Comment by kwanghoon** [comment]
@moonyoungJo 
I will take a look at this issue, and will get back soon.

**Comment by kwanghoon** [comment]
@moonyoungJo 
This issue has been resolved.
