### ISSUE TITLE
'@assert문 사용 시 궁금한 점

### ISSUE THREAD

**Issue by wldyd1003** [kwanghoon/MySmallBasic#126]
Math 라이브러리의 함수들을 사용을 하게 되면 부동소수점 오차가 생길 수 있는 함수가 몇 가지 있습니다.

예를 들면, Math.Sin( Math.Pi / 6 )의 경우 결과로 0.5가 예상되지만 
실제로는 0.49999999999999994가 리턴됩니다.

따라서, 
'@assert Math.Sin(Math.Pi/6) = 0.5
를 추가하였을 때 문제가 생길 것으로 예상됩니다.

이런 경우에는 '@assert문을 어떻게 사용해야 할까요?

**Comment by wldyd1003** [comment]
@kwanghoon

**Comment by kwanghoon** [comment]
@wldyd1003 Microsoft SmallBasic 결과를 활용.
'@assert Math.Sin(Math.Pi/6) =  0.49999999999999994
