### ISSUE TITLE
MySmallBasic GUI 실행 시 창이 바로 종료되는 문제

### ISSUE THREAD

**Issue by Kim-Gayoung** [kwanghoon/MySmallBasic#131]
MySmallBasic GUI에서 실행버튼을 눌렀을 때 화면이 나왔다가 바로 종료되는 문제가 있습니다.
@kwanghoon @moonyoungJo 

콘솔창에는 다음과 같이 출력됩니다.

cmd.exe
/c
start java.exe
com.coducation.smallbasic.MySmallBasicMain
-gui
D:\git\MySmallBasic\MySmallBasic\regressiontest\Recursive_fib.sb
USERDOMAIN_ROAMINGPROFILE : DESKTOP-TQ03DM6
LOCALAPPDATA : C:\Users\user\AppData\Local
PROCESSOR_LEVEL : 6
USERDOMAIN : DESKTOP-TQ03DM6
FPS_BROWSER_APP_PROFILE_STRING : Internet Explorer
LOGONSERVER : \\DESKTOP-TQ03DM6
JAVA_HOME : C:\Program Files\Java\jdk1.8.0_121
FSHARPINSTALLDIR : C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\
SESSIONNAME : Console
ALLUSERSPROFILE : C:\ProgramData
PROCESSOR_ARCHITECTURE : AMD64
PSModulePath : C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\WindowsPowerShell\Modules\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage\
SystemDrive : C:
OneDrive : C:\Users\user\OneDrive
APPDATA : C:\Users\user\AppData\Roaming
Classpath : C:\Program Files\Java\jdk1.8.0_121\lib\tool.jar
STACK_ROOT : C:\sr
USERNAME : user
ProgramFiles(x86) : C:\Program Files (x86)
CommonProgramFiles : C:\Program Files\Common Files
Path : C:/Program Files/Java/jre1.8.0_141/bin/server;C:/Program Files/Java/jre1.8.0_141/bin;C:/Program Files/Java/jre1.8.0_141/lib/amd64;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Java\jdk1.8.0_121\bin;C:\Program Files\Git\cmd;C:\Program Files\Java\jre1.8.0_121\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\PuTTY\;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Program Files\MySQL\MySQL Server 5.7\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Users\user\AppData\Roaming\local\bin;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;;C:\Users\user\eclipse\jee-neon\eclipse;
FPS_BROWSER_USER_PROFILE_STRING : Default
PATHEXT : .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
OS : Windows_NT
COMPUTERNAME : DESKTOP-TQ03DM6
PROCESSOR_REVISION : 5e03
CommonProgramW6432 : C:\Program Files\Common Files
CLASSPATH : .//bin;.//lib/jansi-1.16.jar;.//lib/jl1.0.1.jar;.//lib/json_simple-1.1.jar;.//lib/org.roboid_1.1.2.jar;.//lib/weka.jar
ComSpec : C:\WINDOWS\system32\cmd.exe
ProgramData : C:\ProgramData
ProgramW6432 : C:\Program Files
HOMEPATH : \Users\user
SystemRoot : C:\WINDOWS
TEMP : C:\Users\user\AppData\Local\Temp
HOMEDRIVE : C:
PROCESSOR_IDENTIFIER : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
USERPROFILE : C:\Users\user
TMP : C:\Users\user\AppData\Local\Temp
CommonProgramFiles(x86) : C:\Program Files (x86)\Common Files
ProgramFiles : C:\Program Files
PUBLIC : C:\Users\Public
NUMBER_OF_PROCESSORS : 8
windir : C:\WINDOWS
=:: : ::\
Exit value: 0

**Comment by Kim-Gayoung** [comment]
컴퓨터 환경변수 CLASSPATH 설정 후 해결

**Comment by Kim-Gayoung** [comment]
컴퓨터 환경변수 CLASSPATH 설정 후 해결

**Comment by kwanghoon** [comment]
@Kim-Gayoung 👍
