### ISSUE TITLE
배열 원소가 교환 되지 않는 문제

### ISSUE THREAD

**Issue by wldyd1003** [kwanghoon/MySmallBasic#134]
MySmallBasic에서 배열 원소의 값을 교환하는 데에 문제가 있습니다.

아래의 코드를 실행해보면 문제를 확인할 수 있습니다.

```
a[1] = 1
a[2] = 2

temp = a[1]
a[1] = a[2]
a[2] = temp

TextWindow.WriteLine(a[1])
TextWindow.WriteLine(a[2])
```

-- MySmallBasicMain으로 실행 시 결과 --
1
1

콘솔 창에서 출력된 메시지를 살펴보면,
Parsing Success. 7 lines.
        a[1] = 1
        a[2] = 2
        temp = a[1]
        `a[2] = a[2]`
        a[2] = temp
        TextWindow.WriteLine(a[1])
        TextWindow.WriteLine(a[2])
$main:
        a[1] = 1
        a[2] = 2
        temp = a[1]
        `a[2] = a[2]`
        a[2] = temp
        TextWindow.WriteLine(a[1])
        TextWindow.WriteLine(a[2])

위와 같이 출력되는데 4번 라인의 코드가 달라지는 문제가 근본적인 원인으로 생각됩니다.

**Comment by wldyd1003** [comment]
@kwanghoon

**Comment by kwanghoon** [comment]
@wldyd1003 
I will take a look at this issue.

**Comment by kwanghoon** [comment]
@wldyd1003 
The reason for this issue is found to be the problem of our parser in parsing array indices. 
I will fix this problem, but it will take some time to finish. 

So, can you commit the Small basic program causing this problem to our GitHub repository?

**Comment by kwanghoon** [comment]
@wldyd1003 @Kim-Gayoung
