### ISSUE TITLE
ArrayV에서 copy() 접근권한 문제

### ISSUE THREAD

**Issue by ssjx10** [kwanghoon/MySmallBasic#181]
패키지 외부에서 copy() 사용 시 접근이 불가합니다. public으로 변경이 필요할 것 같습니다.
![image](https://user-images.githubusercontent.com/22792308/35206235-989c7462-ff7e-11e7-90b4-ea71a416822f.png)

**Comment by kwanghoon** [comment]
@ssjx10 Fixed by the commit a87994d
