### ISSUE TITLE
c11 구문 후보 데이터 파일 형식 vs. smallbasic 구문 후보 데이터 파일 형식

### ISSUE THREAD

**Issue by kwanghoon** [kwanghoon/MySmallBasic#248]
https://github.com/kwanghoon/MySmallBasic/blob/56b402ed8c15784c7bb22bad79094213499c4d67/MySmallBasic/src/com/coducation/smallbasic/syncomp/SocketCommunication.java#L52C1-L53

c11 구문 후보 데이터 파일 형식 vs. smallbasic 구문 후보 데이터 파일 형식

두 파일 형식이 다른것 같아요...

@H-sooyeon

**Comment by kwanghoon** [comment]
@H-sooyeon 
아~ 파일 이름이 c11-data-state-collection.txt 이군요.
착각했어요, c11-data-collection.txt로 ...

**Comment by H-sooyeon** [comment]
감사합니다
날짜: 2023.06.25 오후 10:39:14 (GMT+09:00)
제목: Re: [kwanghoon/MySmallBasic] c11 구문 후보 데이터 파일 형식 vs. smallbasic 구문 후보 데이터 파일 형식 (Issue #248)

@H-sooyeon
아~ 파일 이름이 c11-data-state-collection.txt 이군요.
착각했어요, c11-data-collection.txt로 ...
