### ISSUE TITLE
비어있는 Sub 루틴에서 NullPointerException

### ISSUE THREAD

**Issue by Kim-Gayoung** [kwanghoon/MySmallBasic#51]
비어있는 Sub 루틴에서 NullPointerException

GraphicsWindow.MouseDown = OnMouseDown

Sub OnMouseDown
	
EndSub

**Comment by kwanghoon** [comment]
해결함 - Commit 14b7886
@KimGa-Young @wldyd1003 @moonyoungJo @Seyeong2 @chosm10 @ssjx10

**Comment by kwanghoon** [comment]
👍
