### ISSUE TITLE
라이브러리 메소드 리턴타입이 void 또는 Value

### ISSUE THREAD

**Issue by Kim-Gayoung** [kwanghoon/MySmallBasic#52]
라이브러리 메소드 리턴타입이 void 또는 Value

'GraphicsWindow.DrawRectangle' 은 반환값이 예상되나, 아무 값도 반환되지 않았습니다.
비정상 종료되는 문제

a = GraphicsWindow.DrawRectangle(10, 10, 50, 50)
TextWindow.WriteLine(a)

b = Math.Abs(-10)
TextWindow.WriteLine(b)

**Comment by kwanghoon** [comment]
해결함 Commit c3cf5fb 참고.
@KimGa-Young @wldyd1003 @moonyoungJo @Seyeong2 @chosm10 @ssjx10
