### ISSUE TITLE
Turtle 라이브러리 실행시 예외 메시지가 뜨는 현상

### ISSUE THREAD

**Issue by kwanghoon** [kwanghoon/MySmallBasic#69]
문영!  Turtle 라이브러리 실행시 예외 메시지가 뜨는 현상을 살펴보고  해결할 수 있으면 시도해보고, 함께 논의해야하면 나머지 멤버들에게 설명할 수 있도록 스스로 이 현상의 원인을 정리해봐.

@KimGa-Young @wldyd1003 @moonyoungJo @Seyeong2 @chosm10 @ssjx10

**Comment by moonyoungJo** [comment]
turtle라이브러리 실행시 예외메시지가 뜨는 현상을 발견하기 위해, 여러 시도를 해보았습니다.
regressiontest/turtle_0.sb 의 거북프렉탈을 그리는 예제에서 turtle이 Move한 뒤, 충분한 시간동안 쉬게(다른 연산을 수행하도록 하였을 때) 예외가 발생하는 빈도가 줄어드는 것을 확인하였습니다. 
그리고, 거북라이브러리의 그리는 속도를 1로 하였을 때는, 예외가 한번도 발생하지 않았습니다.
즉, 패널을 repaint()하는 빈도에 따라 예외가 발생하는 것을 알 수 있습니다.

발생하는 예외의 메시지는 다음과 같습니다
Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at com.coducation.smallbasic.lib.GraphicsWindow$Panel.paintComponent(GraphicsWindow.java:305)
	at javax.swing.JComponent.paint(Unknown Source)
...

위의 사실로 유추해 볼 때, 스몰베이직 해석기의 문제가 아닌것으로 보입니다.  
GraphicsWindow의 그림을 그리는 panel의 paintComponent() 메소드에서, for (Cmd cmd : cmdList)부분에서 예외가 던져집니다.
ConcurrentModificationException는 변경이 일어나서는 안되는 부분(Collection..)에서, 변경이 있을 때, 발생하는 예외입니다.(예를 들면, iterator가 가리키는 ArrayList가 변경이 되었을 때) 
for문에서 cmdList가 ArrayList이므로, iterator로 for문을 돌리게 됩니다. 이때, 다른 쓰레드또는 for문안에서 cmdList를 변경해서 예외가 발생된걸로 보입니다. 

해결방법으로는, 만약 cmdList가 패널을 그릴 때, 변경되어도 상관없다면, for (Cmd cmd : cmdList)를 iterator가 가리키는 ArrayList의 변경이 없는, for (Cmd cmd : ((ArrayList<Cmd>)cmdList.clone())) 로 바꾸거나, CopyOnWriteArrayList로 cmdList를 변경하는 방법으로 해결될 것 같습니다.
만약 cmdList가 패널을 그릴때, 변경되어서는 안된다면, 동기화 시키는 방법으로 해결될 것 같습니다.

혹시 더 좋은 방법이 있을지 논의해보아도 좋을 것 같습니다.

**Comment by kwanghoon** [comment]
좋은 의견! 스레드 문제가 아닌가 싶다.
👍 
@moonyoungJo @KimGa-Young
