### ISSUE TITLE
File lib관련 문자인코딩

### ISSUE THREAD

**Issue by ssjx10** [kwanghoon/MySmallBasic#71]
small basic
기본인코딩 UTF-8

sb에서는 File.AppendContents 사용할 경우 메모장 문자인코딩을 UTF-8로 변경
java에서는 isr = new OutputStreamWriter(new FileOutputStream("C://Users//JSW//Desktop//5555.txt", true)); 사용할 경우 메모장 문자인코딩을 기존에 써져있던 인코딩으로 사용
파일이 존재하지않을 경우는 기본문자인코딩 사용

**Comment by kwanghoon** [comment]
마이크로소프트 스몰베이직 프로그램의 동작 방식대로 UTF-8을 기본 인코딩으로 사용하기로 함.
👍

**Comment by kwanghoon** [comment]
마이크로소프트 스몰베이직 프로그램의 동작 방식대로 UTF-8을 기본 인코딩으로 사용하기로 함.
