### ISSUE TITLE
property값을 설정할 때 나타나는 문제

### ISSUE THREAD

**Issue by moonyoungJo** [kwanghoon/MySmallBasic#73]
//예제코드1_범위를 가지는 property
Turtle.Speed = 11
TextWindow.WriteLine(Turtle.Speed)

->Turtle.Speed는 1에서 10까지의 값만을 가지기 때문에, 출력결과로 10이 출력되어야합니다.

//예제코드2_값을 지정해주면, 어떤일을 바로 하는 property
Turtle.Move(100)
Turtle.Angle = 90

-> 거북이의 각도를 90도로 설정하면 바로 90도로 회전한 모습이 출력되어야 합니다.

위와 같이 property값을 지정해주고 나서, 어떤 작업(범위확인 등)이 필요한 경우, 현재는 할 수 있는 방법이 없습니다.

**Comment by kwanghoon** [comment]
특정 poperty를 설정하면 (예: Turtle.Angle =90) 
설정된 바로 다음에 notifyFieldAssign() 메소드가 호출되도록 해석기를 구현해놓았어요.
따라서 notifyFieldAssign()의 인자로 설정한 Properyty 이름을 넘겨주네요. 여러 개의 Property들 중
어느 것이 설정되었느지 알 수 있도록. 
이 메소드 안에서 "거북이의 각도를 바로 90도로 회전한 모습을 출력하는" 코드가 들어가면 됩니다.
👍 
@moonyoungJo @KimGa-Young
