### ISSUE TITLE
CollisionPhysics.sb / Tetris.sb / Sockoban.sb 실행시 에러

### ISSUE THREAD

**Issue by kwanghoon** [kwanghoon/MySmallBasic#79]
현재 SampleCollisionPhysics.sb를 실행하면 Array.GetItemCount 함수에서 에러가 나고
Sample/Tetris.sb를 실행하면 Program 라이브러리가 없는 에러가 나며
Sample/Sokoban.sb를 실행하면 ImageList 라이브러리에서 미구현으로 인한 에러가 납니다.
담당자들은 확인하세요~

@KimGa-Young @wldyd1003 @moonyoungJo @Seyeong2 @chosm10 @ssjx10

**Comment by Seyeong2** [comment]
SampleCollisionPhysics.sb 실행해봤는데 Array.GetItemCount(balls)에서 변수 balls를 배열로 인식하지 못합니다. Array.IsArray(balls)로 확인 시 false가 나왔습니다.

**Comment by kwanghoon** [comment]
디버깅해보니까 Array.GetItemCount 메소드에서 분명히 args의 크기가 1로 나오는데 args.get(0)가 null로 설정되어 있더라. balls를 제대로 넘겨주었다면 args.get(0)가 null이 아닐텐데. 이 부분을 더 보고 어떤 상황인지 파악해볼래?

	public static Value GetItemCount(ArrayList<Value> args){
		
		if(args.size()==1){
			
			Value arg = args.get(0);
			ArrayV arr;
			
			if(arg instanceof ArrayV){
				arr = (ArrayV)arg;
			}

@Seyeong2

**Comment by kwanghoon** [comment]
CollisionPhysics.sb의 414~417 라인에
아래와 같이 동작하는 것을 확인했다. 배열 인자로 null을 받으면 아직 그 배열의 원소를 만들지 않은 상황이다. 그러한 경우도 고려하도록 Array 라이브러리를 만들면 되겠다.

'Reset new balls
Sub reset
  TextWindow.WriteLine(balls)  ===> balls 배열은 아직 정의되어 있지 않아서 아무것도 출력하지 않음
  mball = Array.GetItemCount(balls)
  TextWindow.WriteLine(mball)     ===> 결과 0
  For i = 1 To mball
    balls[i] = ""
    If (istart Or i > nball) Then
      Xpos[i] = ""
      Ypos[i] = ""

@Seyeong2 @KimGa-Young

**Comment by kwanghoon** [comment]
Sokoban 데모 애니메이션에서 Microsoft Smallbasic에서 실행한 모습과 다르게 진행되는 문제
