### ISSUE TITLE
ImageList와 GraphicsWindow, Shapes

### ISSUE THREAD

**Issue by moonyoungJo** [kwanghoon/MySmallBasic#83]
ImageList가 가진 image_List(이미지리스트를 가지는 해시맵)가 GraphicsWindow와 Shpaes와 공유되어야할 것 같습니다.

- 예제코드1_ImageList와 GraphicsWindow
ImagePath = "C:\Users\Public\Pictures\Sample Pictures\Tulips.jpg"
Image = ImageList.LoadImage(ImagePath)
TextWindow.WriteLine(Image)
GraphicsWindow.DrawImage(Image, 0, 0)

설명 : 3번째 줄의 결과는 ImageList1입니다. 그리고 4줄이 GraphicsWindow.DrawImage("ImageList1", 0, 0)으로 바꿔도 똑같이 실행되는 것으로 보아, DrawImage의 첫번째 인자가 문자열 ImageList로 시작되면, ImageList클래스의 image_List (이미지 해시맵)에서 가져와서 실행되게 만들어야 할 것 같습니다.

- 예제코드2_ImageList와 Shape
imagePath = "C:\Users\Administrator\git\MySmallBasic\MySmallBasic\resource\Turtle.png"
imagelistID = ImageList.LoadImage(imagePath)
imageID = Shapes.AddImage(imagelistID)
Shapes.Move(imageID, 300, 0)

설명 : 예제코드1의 설명과 비슷하게, Shape의 AddImage메소드의 경우 인자가 imageListID인지 확인하고, 만약 맞다면, ImageList클래스의 image_List에서 찾아와서 써야할 것 같습니다.

**Comment by kwanghoon** [comment]
Good! 👍
