### ISSUE TITLE
Shapes.Move와 Shapes.Rotate

### ISSUE THREAD

**Issue by moonyoungJo** [kwanghoon/MySmallBasic#84]
코드1
image = Shapes.AddImage("C:\Users\Administrator\git\MySmallBasic\MySmallBasic\resource\Turtle.png")
Shapes.Move(image, 100, 100)

코드2
image = Shapes.AddImage("C:\Users\Administrator\git\MySmallBasic\MySmallBasic\resource\Turtle.png")
Shapes.Rotate(image, 90)

로컬이미지를 로드해서, Move와 Rotate를 할 경우 잘 되지 않아요!
Turtle클래스 구현을 위해서 위의 두 메소드가 필요합니다.

**Comment by kwanghoon** [comment]
Good! 👍
