### ISSUE TITLE
필드값 입력받아서 대입할 때 나타나는 예외

### ISSUE THREAD

**Issue by moonyoungJo** [kwanghoon/MySmallBasic#87]
스몰베이직_가져오기_VLF523
40~42번째줄의 코드

TextWindow.WriteLine ("How fast?")
d = TextWindow.Read()
Turtle.Speed = d

필드 인자를 TextWindow.ReadNumber()으로 안읽고, TextWindow.Read()로 읽어서 대입을해도 스몰베이직프로그램에서는 잘돌아가는데, MySmallBasic에서는 예외처리가 됩니다. 해결방법이 있는지 궁금합니다.

d에 숫자가 아닌값을 입력했으면, Turtle.Speed가 1로 설정됩니다. 10보다 큰 수를 입력하였으면, 10으로 설정됩니다.

**Comment by kwanghoon** [comment]
Turtle.java의 468 라인에서 
getValue()의 결과가 StrV인데 DoubleV로 캐스팅하려다 에러가 발생했단다.
확인 바란다.
간단하고 재미있는 터틀 그래픽스 예제인것 같다!! 👍 
@moonyoungJo

**Comment by kwanghoon** [comment]
그리고 내가 확인해야하는 이슈를 올릴 때 
@kwanghoon 이라고 멘션을 해주면 
나한테 이메일을 보내게 된단다. 
@moonyoungJo
